# Generated by Django 5.2 on 2025-05-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='cake',
            new_name='favoritecake',
        ),
        migrations.AlterField(
            model_name='birthday',
            name='sign',
            field=models.CharField(max_length=20),
        ),
    ]
