# Generated by Django 5.2 on 2025-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cake_birthday_favoritecake_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('presents', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='birthday',
            name='parties',
            field=models.ManyToManyField(to='main_app.party'),
        ),
    ]
